app_name: "yt-clipper-api"
env: "local"

DBConfig:
  Host: ""
  Port: "5432"
  Username: ""
  Password: ""
  Name: ""
  MaxOpenConn: 4
  MaxConnLifeTime: 300

OpenAI:
  apiKey: ""

Minio:
  endpoint: "192.168.1.122:9000"
  region: "us-east-1"
  bucket: "yt-clips"
  accessKey: ""
  secretKey: ""

prefixTTSVoice: "youtube"
BaseURL: "http://localhost:8080"
